<?php
// Register Custom Post Types
function tp_register_custom_post_types() {

    // Register Brand Post Type
    $labels = array(
        'name'                  => _x( 'Brands', 'Post Type General Name', 'text_domain' ),
        'singular_name'         => _x( 'Brand', 'Post Type Singular Name', 'text_domain' ),
        'menu_name'             => __( 'Brands', 'text_domain' ),
        'name_admin_bar'        => __( 'Brand', 'text_domain' ),
        'archives'              => __( 'Brand Archives', 'text_domain' ),
        'attributes'            => __( 'Brand Attributes', 'text_domain' ),
        'parent_item_colon'     => __( 'Parent Brand:', 'text_domain' ),
        'all_items'             => __( 'All Brands', 'text_domain' ),
        'add_new_item'          => __( 'Add New Brand', 'text_domain' ),
        'add_new'               => __( 'Add New', 'text_domain' ),
        'new_item'              => __( 'New Brand', 'text_domain' ),
        'edit_item'             => __( 'Edit Brand', 'text_domain' ),
        'update_item'           => __( 'Update Brand', 'text_domain' ),
        'view_item'             => __( 'View Brand', 'text_domain' ),
        'view_items'            => __( 'View Brands', 'text_domain' ),
        'search_items'          => __( 'Search Brand', 'text_domain' ),
        'not_found'             => __( 'Not found', 'text_domain' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
        'featured_image'        => __( 'Featured Image', 'text_domain' ),
        'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
        'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
        'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
        'insert_into_item'      => __( 'Insert into brand', 'text_domain' ),
        'uploaded_to_this_item' => __( 'Uploaded to this brand', 'text_domain' ),
        'items_list'            => __( 'Brands list', 'text_domain' ),
        'items_list_navigation' => __( 'Brands list navigation', 'text_domain' ),
        'filter_items_list'     => __( 'Filter brands list', 'text_domain' ),
    );
    $args = array(
        'label'                 => __( 'Brand', 'text_domain' ),
        'description'           => __( 'Post Type Description', 'text_domain' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => 'tailored-pages',
        'menu_position'         => 6,
        'menu_icon'             => 'dashicons-store',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'brand', $args );

    // Register Listing Page Post Type
    $labels = array(
        'name'                  => _x( 'Listing Pages', 'Post Type General Name', 'text_domain' ),
        'singular_name'         => _x( 'Listing Page', 'Post Type Singular Name', 'text_domain' ),
        'menu_name'             => __( 'Listing Pages', 'text_domain' ),
        'name_admin_bar'        => __( 'Listing Page', 'text_domain' ),
        'archives'              => __( 'Listing Page Archives', 'text_domain' ),
        'attributes'            => __( 'Listing Page Attributes', 'text_domain' ),
        'parent_item_colon'     => __( 'Parent Listing Page:', 'text_domain' ),
        'all_items'             => __( 'All Listing Pages', 'text_domain' ),
        'add_new_item'          => __( 'Add New Listing Page', 'text_domain' ),
        'add_new'               => __( 'Add New', 'text_domain' ),
        'new_item'              => __( 'New Listing Page', 'text_domain' ),
        'edit_item'             => __( 'Edit Listing Page', 'text_domain' ),
        'update_item'           => __( 'Update Listing Page', 'text_domain' ),
        'view_item'             => __( 'View Listing Page', 'text_domain' ),
        'view_items'            => __( 'View Listing Pages', 'text_domain' ),
        'search_items'          => __( 'Search Listing Page', 'text_domain' ),
        'not_found'             => __( 'Not found', 'text_domain' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
        'featured_image'        => __( 'Featured Image', 'text_domain' ),
        'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
        'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
        'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
        'insert_into_item'      => __( 'Insert into listing page', 'text_domain' ),
        'uploaded_to_this_item' => __( 'Uploaded to this listing page', 'text_domain' ),
        'items_list'            => __( 'Listing Pages list', 'text_domain' ),
        'items_list_navigation' => __( 'Listing Pages list navigation', 'text_domain' ),
        'filter_items_list'     => __( 'Filter listing pages list', 'text_domain' ),
    );
    $args = array(
        'label'                 => __( 'Listing Page', 'text_domain' ),
        'description'           => __( 'Post Type Description', 'text_domain' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => 'tailored-pages',
        'menu_position'         => 7,
        'menu_icon'             => 'dashicons-list-view',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'listing-page', $args );

    // Register Landing Page Post Type
    $labels = array(
        'name'                  => _x( 'Landing Pages', 'Post Type General Name', 'text_domain' ),
        'singular_name'         => _x( 'Landing Page', 'Post Type Singular Name', 'text_domain' ),
        'menu_name'             => __( 'Landing Pages', 'text_domain' ),
        'name_admin_bar'        => __( 'Landing Page', 'text_domain' ),
        'archives'              => __( 'Landing Page Archives', 'text_domain' ),
        'attributes'            => __( 'Landing Page Attributes', 'text_domain' ),
        'parent_item_colon'     => __( 'Parent Landing Page:', 'text_domain' ),
        'all_items'             => __( 'All Landing Pages', 'text_domain' ),
        'add_new_item'          => __( 'Add New Landing Page', 'text_domain' ),
        'add_new'               => __( 'Add New', 'text_domain' ),
        'new_item'              => __( 'New Landing Page', 'text_domain' ),
        'edit_item'             => __( 'Edit Landing Page', 'text_domain' ),
        'update_item'           => __( 'Update Landing Page', 'text_domain' ),
        'view_item'             => __( 'View Landing Page', 'text_domain' ),
        'view_items'            => __( 'View Landing Pages', 'text_domain' ),
        'search_items'          => __( 'Search Landing Page', 'text_domain' ),
        'not_found'             => __( 'Not found', 'text_domain' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
        'featured_image'        => __( 'Featured Image', 'text_domain' ),
        'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
        'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
        'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
        'insert_into_item'      => __( 'Insert into landing page', 'text_domain' ),
        'uploaded_to_this_item' => __( 'Uploaded to this landing page', 'text_domain' ),
        'items_list'            => __( 'Landing Pages list', 'text_domain' ),
        'items_list_navigation' => __( 'Landing Pages list navigation', 'text_domain' ),
        'filter_items_list'     => __( 'Filter landing pages list', 'text_domain' ),
    );
    $args = array(
        'label'                 => __( 'Landing Page', 'text_domain' ),
        'description'           => __( 'Post Type Description', 'text_domain' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => 'tailored-pages',
        'menu_position'         => 8,
        'menu_icon'             => 'dashicons-admin-page',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'landing-page', $args );

    // Register Thank You Page Post Type
    $labels = array(
        'name'                  => _x( 'Thank You Pages', 'Post Type General Name', 'text_domain' ),
        'singular_name'         => _x( 'Thank You Page', 'Post Type Singular Name', 'text_domain' ),
        'menu_name'             => __( 'Thank You Pages', 'text_domain' ),
        'name_admin_bar'        => __( 'Thank You Page', 'text_domain' ),
        'archives'              => __( 'Thank You Page Archives', 'text_domain' ),
        'attributes'            => __( 'Thank You Page Attributes', 'text_domain' ),
        'parent_item_colon'     => __( 'Parent Thank You Page:', 'text_domain' ),
        'all_items'             => __( 'All Thank You Pages', 'text_domain' ),
        'add_new_item'          => __( 'Add New Thank You Page', 'text_domain' ),
        'add_new'               => __( 'Add New', 'text_domain' ),
        'new_item'              => __( 'New Thank You Page', 'text_domain' ),
        'edit_item'             => __( 'Edit Thank You Page', 'text_domain' ),
        'update_item'           => __( 'Update Thank You Page', 'text_domain' ),
        'view_item'             => __( 'View Thank You Page', 'text_domain' ),
        'view_items'            => __( 'View Thank You Pages', 'text_domain' ),
        'search_items'          => __( 'Search Thank You Page', 'text_domain' ),
        'not_found'             => __( 'Not found', 'text_domain' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
        'featured_image'        => __( 'Featured Image', 'text_domain' ),
        'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
        'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
        'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
        'insert_into_item'      => __( 'Insert into thank you page', 'text_domain' ),
        'uploaded_to_this_item' => __( 'Uploaded to this thank you page', 'text_domain' ),
        'items_list'            => __( 'Thank You Pages list', 'text_domain' ),
        'items_list_navigation' => __( 'Thank You Pages list navigation', 'text_domain' ),
        'filter_items_list'     => __( 'Filter thank you pages list', 'text_domain' ),
    );
    $args = array(
        'label'                 => __( 'Thank You Page', 'text_domain' ),
        'description'           => __( 'Post Type Description', 'text_domain' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => 'tailored-pages',
        'menu_position'         => 9,
        'menu_icon'             => 'dashicons-format-aside',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'thank-you', $args );

}
add_action( 'init', 'tp_register_custom_post_types', 0 );
?>
